# -*- coding: utf-8 -*-
"""sentiment analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yrY5DoSZ7Ocq0qpbTyAimOrSIbbcpTYx
"""

import nltk
from nltk.sentiment import SentimentIntensityAnalyzer

# Download the VADER lexicon if not already downloaded
nltk.download('vader_lexicon')

# Initialize the VADER sentiment analyzer
sia = SentimentIntensityAnalyzer()

# Example customer reviews
reviews = [
    "I love this product! It's amazing.",
    "The customer service was terrible. I'm never buying from them again.",
    "The quality of the product is good, but the price is too high.",
    "I had a mixed experience with this company. The delivery was fast, but the product was damaged."
]

# Analyze sentiment for each review
for review in reviews:
    sentiment_scores = sia.polarity_scores(review)
    sentiment = sentiment_scores['compound']
    
    if sentiment >= 0.05:
        sentiment_label = 'Positive'
    elif sentiment <= -0.05:
        sentiment_label = 'Negative'
    else:
        sentiment_label = 'Neutral'
    
    print(f"Review: {review}")
    print(f"Sentiment: {sentiment_label}")
    print()